# Generated by Django 4.0.4 on 2022-06-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staffurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffurl',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
